var I18N = {};

I18N.zh = {};

I18N.zh = {
    title: {
        static: {
            "Continue generating": "继续生成",
            "Welcome to our script! Would you like to set the language to English or Chinese? Press OK for English and Cancel for Chinese. You can change this later in the script menu.": "欢迎来到我们的脚本！您想将语言设置为英语还是中文？按确定选择英语，按取消选择中文。您稍后可以在脚本菜单中更改此设置。",
            "Is this conversation helpful so far?": "到目前为止，这次谈话有帮助吗？",
            "network error": "网络错误",
            "There was an error generating a response": "出现了生成响应的错误。",
            "ChatGPT can make mistakes. Consider checking important information.": "ChatGPT 可能会出错。考虑检查重要信息。",
            "Today": "今日",
            "Yesterday": "昨日",
            "Previous 7 Days": "最近7日",
            "Upgrade your plan": "升级您的计划",
            "Message ChatGPT…": "给ChatGPT发消息…",
            "Send message": "发送消息",
            "Free": "免费",
            "Your current plan": "您当前的计划",
            "For people just getting started with ChatGPT": "适用于刚开始使用ChatGPT的用户",
            "Unlimited messages, interactions, and history": "无限的消息、交互和历史记录",
            "Access to our GPT-3.5 model": "访问我们的GPT-3.5模型",
            "Access on Web, iOS, and Android": "支持Web、iOS和Android",
            "Have an existing plan? See billing help": "已有现有计划？请查看计费帮助",
            "Plus": "高级版",
            "Sign up for waitlist": "加入等待列表",
            "Everything in Free, and:": "包含所有免费版功能，以及：",
            "Access to GPT-4, our most capable model": "访问GPT-4，我们最强大的模型",
            "Browse, create, and use GPTs": "浏览、创建和使用GPTs",
            "Access to additional tools like DALL·E, Browsing, Advanced Data Analysis and more": "访问其他工具，如DALL·E、浏览、高级数据分析等",
            "Need more capabilities? See ": "需要更多功能？查看",
            "ChatGPT Enterprise": "ChatGPT企业版",
            "Share link to Chat": "分享聊天链接",
            "Messages you send after creating your link won\"t be shared. Anyone with the URL will be able to view the shared chat.": "创建链接后发送的消息不会被分享。任何拥有URL的人都能查看共享的聊天。",
            "More Info": "更多信息",
            "Share your name": "分享您的姓名",
            "Copy Link": "复制链接",
            "Great for everyday tasks": "适用于日常任务",
            "Our smartest and most capable model. Includes DALL·E, browsing and more.": "我们最聪明、最强大的模型。包括DALL·E、浏览等功能。",
            "Upgrade to Plus": "升级到高级版",
            "Open sidebar": "打开侧边栏",
            "Close sidebar": "关闭侧边栏",
            "Help & FAQ": "帮助与常见问题解答",
            "Release notes": "发行说明",
            "Terms & policies": "条款与政策",
            "Keyboard shortcuts": "键盘快捷键",
            "Open new chat": "打开新聊天",
            "Focus chat input": "聚焦聊天输入",
            "Copy last code block": "复制上一个代码块",
            "Copy last response": "复制上一个响应",
            "Set custom instructions": "设置自定义指令",
            "Toggle sidebar": "切换侧边栏",
            "Delete chat": "删除聊天",
            "Show shortcuts": "显示快捷键",
        }
    }
}